# syntax=docker/dockerfile:1
FROM node:22-bullseye-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
    libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libgtk-3-0 \
    libasound2 libxshmfence1 libx11-xcb1
WORKDIR /refresh-osm
COPY package.json package-lock.json ./
RUN npm install --production
COPY . .
CMD ["node", "osm.js"]
